[wazuh_manager]
wazuh ansible_host=192.168.40.20

[proxmox_nodes]
enode-a ansible_host=192.168.40.10
enode-b ansible_host=192.168.40.11
enode-c ansible_host=192.168.40.12

[k8s_control_plane]
k8s-master-1 ansible_host=192.168.20.10
k8s-master-2 ansible_host=192.168.20.11
k8s-master-3 ansible_host=192.168.20.12

[k8s_workers]
k8s-worker-1 ansible_host=192.168.20.20
k8s-worker-2 ansible_host=192.168.20.21

[all_agents:children]
proxmox_nodes
k8s_control_plane
k8s_workers

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
