---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin-password: AgBmgdBb/dL0GjLEr4QSiSquED6Nv+LDT9mg7oogyO1tvCue5/T9ITK3r2UQ8aw+HwON5pm6xNO/m82a0OQnfr3rW1L0DkyrU/eTFi1IPyqM8oQLK8Sp+qMhJ9yfllhgoGfxzYdq3t/i+uitqgs9Dm4yt/0YRK7MDLtdcQqj3BJci/ejvQ6uW9kmJrrCZ6PgeC4WRiNMsELRHVaBIuEoWtf0VL7yotLwWgOwkPlqgv+SbvwICMe48/yZDjzy7COxXMVJU3wLHHosyYc5Y+4XWfWqUjL4mKXZijCwbcIYOh6ARWPIg8um7H/foKEbTw0dKxbseCSNg5dTbQogeArLS1PAuddxX+/6ZZft9ZgJXicXZjtxxtTdAowc0Y5rz7ts7BRtGE3luURkCLjIiyQoTx/sCurVPGZVsOpclWWsotcs7fW3FIdEMq5WJnRSP8oCNCFQbPt5y8fn8BZa1RXweIR+gLxoFrKyOW7DSEGuyNlna1o7YZYFSRvy2QoGir5IAnYL8zVF9L8cBwku+7guRM+9UDsWIDi5TPeoGwCnMdvOltk1HEFyhWoztex1qDsVzqHsgNGci8W5CGoi3B5x6Wlp9s/NsWG2NLPV9ag0vnvVLEwaeMCup5MJ5+Mqk+HxA53cASKhxkvTS2UpHuivwkbA27KftGWjFkr5iCOTRH21QmHrQPVMQowItcNI1M2kh/jy6xJtboAtjQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
