---
- name: "Add Wazuh GPG key"
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    dest: /tmp/GPG-KEY-WAZUH
    mode: '0644'

- name: "Import Wazuh GPG key into keyring"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gpg --no-default-keyring \
          --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg \
          --import /tmp/GPG-KEY-WAZUH && \
      chmod 644 /usr/share/keyrings/wazuh.gpg
    creates: /usr/share/keyrings/wazuh.gpg

- name: "Add Wazuh repository"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
    state: present
    filename: wazuh

- name: "Install Wazuh Agent"
  ansible.builtin.apt:
    name: "wazuh-agent={{ wazuh_agent_version }}"
    state: present
    update_cache: true

- name: "Configure Manager IP in ossec.conf"
  ansible.builtin.replace:
    path: /var/ossec/etc/ossec.conf
    regexp: 'MANAGER_IP'
    replace: "{{ wazuh_agent_manager_ip }}"
  notify: Restart Wazuh Agent

- name: "Ensure Wazuh agent is enabled and running"
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: true
    state: started
