---
- name: "Wazuh Dashboard Configuration"
  hosts: wazuh_manager
  become: yes
  roles:
    - wazuh_dashboard_config

- name: "Wazuh Agent Deployment & Parity"
  hosts: all_agents
  become: yes
  roles:
    - wazuh_agent
