apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../../base/nginx-test
images:
- name: nginx
  newName: docker.io/library/nginx
  newTag: stable
- name: docker.io/nginx
  digest: sha256:d9911e5ac94c1905ffd34a582d01430224aed6954cb4a788b7877114bf0c1cb1
patches:
- path: replica-patch.yaml
  target:
    kind: Deployment
    name: nginx-test
- path: resources-patch.yaml
  target:
    kind: Deployment
    name: nginx-test
- path: loadbalancer-patch.yaml
  target:
    kind: Service
    name: nginx-test
