apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.0
    helm:
      values: |
        config:
          argocd:
            insecure: true
        extraEnv:
          - name: ARGOCD_IMAGE_UPDATER_GITCREDS
            valueFrom:
              secretKeyRef:
                name: argocd-image-updater-secret
                key: github.token
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
