name: Deploy Wazuh Rules
on:
  push:
    branches:
      - main
    paths:
      - 'etc/rules/local_rules.xml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Rules to Wazuh
        run: |
          # Using the absolute path discovered via find
          sudo cp -v /home/github-runner/actions-runner/_work/homelab/homelab/etc/rules/local_rules.xml /var/ossec/etc/rules/local_rules.xml
          
      - name: Restart Wazuh Manager
        run: |
          sudo systemctl restart wazuh-manager
          
      - name: Restart Wazuh Manager
        run: |
          sudo systemctl restart wazuh-manager
          echo "Deployment successful: Wazuh Manager restarted with new rules."